export enum FormErrors {
    INVALID_EMAIL_ADDRESS = 'errors.invalidEmailAddress',
    REQUIRED_FIELD = 'errors.requiredField',
    MAX_LENGTH_OVERFLOW = 'errors.maxLength',
    MIN_LENGTH_REQUIRED = 'errors.minLength',
    FIELDS_DOESNT_MATCH = "errors.fields_doesnt_match",
    NOT_A_NUMBER = 'errors.notANumber',
    NOT_AN_INTEGER = "errors.notAnInteger",
    MIN_VALUE_OVERFLOW = 'errors.minValueOverflow',
    MAX_VALUE_OVERFLOW = 'errors.maxValueOverflow',
    INVALID_FORMAT = 'errors.invalidFormat',
    INVALID_OPTION = 'errors.invalidOption',
    MIN_DATE_OVERFLOW = 'errors.minDateOverflow',
    MAX_DATE_OVERFLOW = 'errors.maxDateOverflow',
    INVALID_PHONE_NUMBER = 'errors.invalidPhoneNumber',
    FILE_SIZE_TOO_LARGE = 'errors.fileSizeTooLarge',
    FILE_EXTENSION_NOT_ALLOWED = 'errors.fileExtensionNotAllowed',
}
